cors:
  originPatterns: "http://localhost:3000,http://localhost:8080,https://erudio.com.br"

security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    username: root
    password: root
  jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: false

  flyway:
    url: jdbc:postgresql://localhost:5432/demo
    user: root
    password: root
    locations: classpath:db/migration

spring-doc:
  pathsToMatch:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/demo
#    username: retaguarda
#    password: retaguarda
#  jpa:
#      hibernate:
#        ddl-auto: none
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQL8Dialect
#      show-sql: false


