#spring.datasource.url=jdbc:mysql://localhost:3306/cursospring?createDatabaseIfNotExist=true&serverTimezone=UTC
#spring.datasource.username=retaguarda
#spring.datasource.password=retaguarda

spring.datasource.url=jdbc:postgresql://localhost:5432/demo

spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
  
  #spring.datasource.driver-class-name=com.mysql.jdbc.Driver
  #spring.jpa.database-platform=org.hibernate.dialect.MySQ5LDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
